stages:
  - build
#  - code-analysis
#  - test
  - deploy
build:
  stage: build
  script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cd ~/web/build/jens-uwe-loessl.de
    - sudo rm -rf -r $CI_COMMIT_REF_NAME
    - mkdir $CI_COMMIT_REF_NAME
    - cd $CI_COMMIT_REF_NAME
    - git clone git@gitlab.x-pensive.de:Jens/jens-uwe-loessl.de.git
    - cd jens-uwe-loessl.de
    - git pull origin $CI_COMMIT_REF_NAME
    - echo build Running
    - yarn install
    - sudo npm run build:dev
  environment:
    name: testing
#ts-lint:
#  stage: code-analysis
#  allow_failure: true
#  script:
#    - cd ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/frontend
#    - echo linting running
#    - yarn run lint
#  environment:
#    name: testing
#  only:
#    - master
#    - development
#backend-tests:
#  stage: test
#  script:
#    - cd ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME
#    - echo test running
#    - cd jens-uwe-loessl.de/backend
#    - vendor/bin/codecept run
#  environment:
#    name: testing
#  only:
#    - master
#    - development
#frontend-tests:
#  stage: test
#  script:
#    - cd ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/frontend
#    - echo ts-unit tests running
#    - yarn run test
#  environment:
#    name: testing
#  only:
#    - master
#    - development
publish:
  stage: deploy
  before_script:
#    - cp ~/web/config/jens-uwe-loessl.de/.env ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/backend/.env
#    - cp ~/web/config/jens-uwe-loessl.de/.env.ts ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/frontend/.env.ts
    - cd ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/
    - sudo rm -rf -r dist
    - yarn run build:prod
  script:
    - sudo rm -rf -r /var/www/jens-uwe-loessl.de
    - mkdir /var/www/jens-uwe-loessl.de
    - cp -r ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/dist /var/www/jens-uwe-loessl.de/
    - cp ~/web/build/jens-uwe-loessl.de/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de/.htaccess /var/www/jens-uwe-loessl.de/.htaccess
    - sudo chmod 777 /var/www/jens-uwe-loessl.de -R
  environment:
    name: staging
    url: https://jens-uwe-loessl.de
  only:
    - master