stages:
  - up

variables:
  ENV_DIR: "/home/gitlab-runner/web/build/jens-uwe-loessl.de"
  BASE_DIR: "$ENV_DIR/$CI_COMMIT_REF_NAME/jens-uwe-loessl.de"
  MAJOR: "1"
  MINOR: "0"
  PATCH: "0"

build:
  stage: up
  script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo $ENV_DIR
    - cd $ENV_DIR
    - sudo rm -rf -r $CI_COMMIT_REF_NAME
    - mkdir $CI_COMMIT_REF_NAME
    - cd $CI_COMMIT_REF_NAME
    - git clone git@gitlab.x-pensive.de:Jens/jens-uwe-loessl.de.git
    - cd $BASE_DIR
    - git pull origin $CI_COMMIT_REF_NAME
    - echo build running
    - docker-compose -f compose/docker-compose.production.yml stop
    - docker-compose -f compose/docker-compose.production.yml up --build
  only:
    - master